const projectData = [
    {
        title: "Hamim's Bank",
        Technology: "TailWind Css || JS DOM",
        description: "Banking System(withdraw, deposit system)",
        live: '../../Banking-system/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/Banking-system',
    },
    {
        title: "Country's information",
        Technology: "TailWind Css || JS DOM || API",
        description: "Search by country name.This is a API project",
        live: '../../country-info-founder/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/country-info-founder',
    },
    {
        title: "Discount calculator",
        Technology: "TailWind Css || JS DOM ",
        description: "After discount button disable ",
        live: '../../Discount-calculator/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/Discount-calculator',
    },
    {
        title: "Flower House",
        Technology: "Bootstrap|| JS DOM ",
        description: "custom data & search functionality",
        live: '../../flower-house/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/flower-house',
    },
    {
        title: "Food Recipes Library",
        Technology: "Tailwind css|| JS DOM || API",
        description: "API project & search functionality with made custom modal with tailwind css",
        live: '../../food-recipes-library/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/food-recipes-library',
    },
    {
        title: "Github repo delete system",
        Technology: "Tailwind css|| JS DOM ",
        description: "Github repository delete system",
        live: '../../Github-ripo-delete-system/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/Github-ripo-delete-system',
    },
    {
        title: "Hami SportsDB",
        Technology: "Tailwind css|| JS DOM || API",
        description: "Find every countries league & team information",
        live: '../../hami-sportsDB/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/hami-sportsDB',
    },
    {
        title: "Phone Picker",
        Technology: "Bootstrap || JS DOM || API",
        description: "search and find information with modal",
        live: '../../phone-picker/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/phone-picker',
    },
    {
        title: "Pin Matcher",
        Technology: "Bootstrap || JS DOM ",
        description: "Pin matcher",
        live: '../../pin-matcher-master',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/pin-matcher-master',
    },
    {
        title: "Pin Matcher",
        Technology: "Bootstrap || JS DOM ",
        description: "Pin matcher",
        live: '../../pin-matcher-master',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/pin-matcher-master',
    },
    {
        title: "Placeholder Comments",
        Technology: "Tailwind css || JS DOM || API",
        description: "from comment find the post",
        live: '../../placeholder-comments/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/placeholder-comments',
    },
    {
        title: "Shopping Cart Calculation",
        Technology: "Bootstrap || JS DOM ",
        description: "Calculation the shopping products price and text",
        live: '../../shopping-cart-calculations/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/shopping-cart-calculations',
    },
    {
        title: "Todo basic",
        Technology: "Bootstrap || JS DOM ",
        description: "Basic todo with table use template string.",
        live: '../../todo-basic/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/todo-basic',
    },
    {
        title: "Todo Advance",
        Technology: "Bootstrap || JS DOM ",
        description: "Advance todo with modal. without use template string",
        live: '../../Todo-advance/index.html',
        CodeLink: 'https://github.com/mdhamimulhaque/javascript-projects/tree/master/Todo-advance',
    },

]